<?php

declare(strict_types=1);

/*
 * This code is under BSD 3-Clause "New" or "Revised" License.
 *
 * PHP version 7 and above required
 *
 * @category  EventManager
 *
 * @author    Divine Niiquaye Ibok <divineibok@gmail.com>
 * @copyright 2019 Biurad Group (https://biurad.com/)
 * @license   https://opensource.org/licenses/BSD-3-Clause License
 *
 * @link      https://www.biurad.com/projects/eventmanager
 * @since     Version 0.1
 */

namespace BiuradPHP\Events\Bridges\Nette;

use Tracy\Helpers;

?>

<h1>Events Listeners (<?php echo count($events); ?>)</h1>
<div class="tracy-inner">
    <div class="tracy-inner-container">
        <table>
            <thead>
                <tr>
                    <th>Events</th>
                    <th>Time Laps</th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($events as $index => $event) : ?>
                    <tr>
                        <td><?php echo Helpers::escapeHtml($event['event']); ?></td>
                        <td><?php echo $event['duration']; ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
